const ActionTypes = {
    ON_STATUS_UPDATE: "ON_STATUS_UPDATE",
    ON_TOGGLE_PANEL_COLLAPSE: "ON_TOGGLE_PANEL_COLLAPSE",
    ON_SOCKET_CLOSED: "ON_SOCKET_CLOSED",
    RECEIVE_OAI_RECORDS: "RECEIVE_OAI_RECORDS",
    RECEIVE_OAI_RECORD: "RECEIVE_OAI_RECORD",
    SET_OAI_RECORD_QUERY: "SET_OAI_RECORD_QUERY",
    ON_OPEN_PANEL: "ON_OPEN_PANEL",
    RECEIVE_DATA_PROVIDER: "RECEIVE_DATA_PROVIDER",
    RECEIVE_REPOSITORY_VALIDATION_RESULTS: "RECEIVE_REPOSITORY_VALIDATION_RESULTS",
    RECEIVE_NEW_REPOSITORY_VALIDATION_RESULTS: "RECEIVE_NEW_REPOSITORY_VALIDATION_RESULTS"
};

export default ActionTypes;