const ActionTypes = {
    ON_STATUS_UPDATE: "ON_STATUS_UPDATE",
    ON_TOGGLE_PANEL_COLLAPSE: "ON_TOGGLE_PANEL_COLLAPSE",
    RECEIVE_REPOSITORIES: "RECEIVE_REPOSITORIES"
};

export default ActionTypes;